steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/constella:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/constella:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'constella'
    - '--image'
    - 'gcr.io/$PROJECT_ID/constella:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--cpu'
    - '0.5'
    - '--memory'
    - '1Gi'
    - '--port'
    - '3000'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '1000'
    - '--max-instances'
    - '1'
    - '--min-instances'
    - '1'

images:
  - 'gcr.io/$PROJECT_ID/constella:$COMMIT_SHA'
